# gen_pinyin.py - 生成板子端拼音输入法字典 pinyin.json（离线、零依赖）
# 说明：沙箱无法访问 GitHub 拼音数据源，这里内置一份常用字拼音表，
#       覆盖日常聊天所需；候选顺序大致按常用度排列。
# 用法：python gen_pinyin.py   -> 生成 pinyin.json

# 拼音 -> 常用汉字列表（第一个尽量是最常用的字）
PINYIN = {
    "a": "啊阿", "ai": "爱矮挨碍", "an": "安暗按", "ang": "昂", "ao": "奥熬傲",
    "ba": "吧把爸八拔", "bai": "白百摆", "ban": "办半班版", "bang": "帮棒",
    "bao": "包宝报抱", "bei": "被北备杯", "ben": "本", "beng": "蹦",
    "bi": "比笔币必毕", "bian": "边便变", "biao": "表", "bie": "别",
    "bin": "宾", "bing": "兵冰并", "bo": "波玻播", "bu": "不布步",
    "ca": "擦", "cai": "才菜采彩", "can": "参残", "cang": "藏",
    "cao": "草操", "ce": "册策", "ceng": "层", "cha": "查茶差插", "chai": "拆",
    "chan": "产铲", "chang": "长常场唱", "chao": "超朝潮", "che": "车",
    "chen": "陈晨沉", "cheng": "成城程称", "chi": "吃迟池持", "chong": "虫充重",
    "chou": "抽愁", "chu": "出初除", "chuan": "穿传船", "chuang": "床创窗",
    "chui": "吹垂", "chun": "春纯", "chuo": "戳", "ci": "词此次",
    "cong": "从丛", "cou": "凑", "cu": "粗促", "cuan": "窜", "cui": "催脆",
    "cun": "村存", "cuo": "错",
    "da": "大答打达", "dai": "带代待", "dan": "但单蛋淡", "dang": "当挡",
    "dao": "到道倒岛", "de": "的得德", "deng": "等灯登", "di": "地第弟底低",
    "dian": "点电店典", "diao": "掉吊调", "die": "跌叠", "ding": "定顶丁",
    "diu": "丢", "dong": "动东冬", "dou": "都斗豆", "du": "度读独毒",
    "duan": "段短端", "dui": "对队", "dun": "顿蹲", "duo": "多朵夺",
    "e": "饿鹅额恶", "en": "恩", "er": "儿而二耳",
    "fa": "发法", "fan": "反饭凡范", "fang": "方房放", "fei": "飞非肥",
    "fen": "分粉奋", "feng": "风封丰蜂", "fo": "佛", "fou": "否",
    "fu": "服父付负福复",
    "ga": "嘎", "gai": "改该概", "gan": "干感敢", "gang": "刚钢港",
    "gao": "高告", "ge": "个哥各格", "gei": "给", "gen": "跟根",
    "geng": "更", "gong": "工公共供", "gou": "够狗构", "gu": "故谷古股",
    "gua": "瓜挂", "guai": "怪乖", "guan": "关管官观", "guang": "光广",
    "gui": "贵归规", "gun": "滚", "guo": "过国果锅",
    "ha": "哈", "hai": "还海害", "han": "汉寒含", "hang": "行航",
    "hao": "好号耗", "he": "和何合河喝", "hei": "黑", "hen": "很狠",
    "heng": "横恒", "hong": "红洪宏", "hou": "后候猴", "hu": "互户湖呼",
    "hua": "化话花华", "huai": "坏怀", "huan": "欢换还环", "huang": "黄皇荒",
    "hui": "会回挥", "hun": "混婚", "huo": "火活货获",
    "ji": "机几记己及急", "jia": "家加价假", "jian": "见建减间简",
    "jiang": "将讲江", "jiao": "叫教交脚角", "jie": "解介借界接",
    "jin": "今金进近", "jing": "经精静京", "jiu": "就九久酒",
    "ju": "局句居巨", "juan": "卷", "jue": "决绝", "jun": "军均",
    "ka": "卡", "kai": "开凯", "kan": "看砍", "kang": "康扛", "kao": "考靠",
    "ke": "可科克客", "ken": "肯", "keng": "坑", "kong": "空恐",
    "kou": "口扣", "ku": "苦库", "kua": "跨", "kuai": "快块", "kuan": "宽",
    "kuang": "狂况", "kui": "亏", "kun": "困", "kuo": "括",
    "la": "拉啦", "lai": "来", "lan": "蓝懒烂", "lang": "浪狼",
    "lao": "老劳", "le": "了乐", "lei": "累泪类", "leng": "冷",
    "li": "力里理立李利", "lian": "连练脸", "liang": "两量亮",
    "liao": "了料", "lie": "列烈", "lin": "林邻", "ling": "另零令灵",
    "liu": "六流留", "long": "龙", "lou": "楼漏", "lu": "路录鹿",
    "lv": "绿率", "luan": "乱", "lun": "论轮", "luo": "落罗",
    "ma": "吗马妈麻", "mai": "买麦卖", "man": "满慢", "mang": "忙盲",
    "mao": "猫毛帽", "me": "么", "mei": "没美每妹", "men": "门闷",
    "meng": "梦猛", "mi": "米密迷", "mian": "面免", "miao": "苗秒",
    "mie": "灭", "min": "民", "ming": "明名命", "miu": "谬",
    "mo": "末摸磨", "mou": "某", "mu": "木目母墓",
    "na": "拿哪那", "nai": "耐乃", "nan": "难南", "nang": "囊",
    "nao": "脑闹", "ne": "呢", "nei": "内", "nen": "嫩", "neng": "能",
    "ni": "你尼泥", "nian": "年念", "niang": "娘", "niao": "鸟",
    "nie": "捏", "nin": "您", "ning": "宁", "niu": "牛", "nong": "农弄",
    "nu": "努", "nv": "女", "nuan": "暖", "nue": "虐", "nuo": "诺",
    "o": "哦", "ou": "偶欧",
    "pa": "怕爬", "pai": "排拍", "pan": "盘盼", "pang": "旁胖",
    "pao": "跑泡", "pei": "培配", "pen": "盆", "peng": "朋碰",
    "pi": "皮匹", "pian": "篇偏", "piao": "票漂", "pie": "撇",
    "pin": "品贫", "ping": "平评屏", "po": "破坡", "pu": "普扑",
    "qi": "起七气其", "qia": "恰", "qian": "前千钱", "qiang": "强墙",
    "qiao": "桥巧", "qie": "切且", "qin": "亲琴", "qing": "青轻情",
    "qiong": "穷", "qiu": "球求", "qu": "去区趣", "quan": "全权",
    "que": "缺却", "qun": "群",
    "ran": "然染", "rang": "让", "rao": "绕", "re": "热", "ren": "人认忍",
    "reng": "仍", "ri": "日", "rong": "容荣", "rou": "肉柔",
    "ru": "如入", "ruan": "软", "rui": "瑞", "run": "润", "ruo": "若",
    "sa": "撒洒", "sai": "塞", "san": "三散", "sang": "桑", "sao": "扫骚",
    "se": "色", "sen": "森", "seng": "僧", "sha": "杀沙", "shai": "晒",
    "shan": "山闪善", "shang": "上商尚", "shao": "少烧", "she": "她社设",
    "shen": "身什深神", "sheng": "生声升省", "shi": "是时事识十",
    "shou": "手首守", "shu": "书数水树", "shua": "刷", "shuai": "帅摔",
    "shuan": "栓", "shuang": "双", "shui": "水谁", "shun": "顺", "shuo": "说",
    "si": "四死思司", "song": "送松", "sou": "搜", "su": "速素",
    "suan": "算酸", "sui": "岁随", "sun": "孙", "suo": "所锁",
    "ta": "他它她踏", "tai": "太台抬", "tan": "谈坦探", "tang": "糖堂",
    "tao": "套逃桃", "te": "特", "teng": "疼腾", "ti": "体替提",
    "tian": "天田甜", "tiao": "跳条", "tie": "贴铁", "ting": "听停庭",
    "tong": "同通童", "tou": "头偷", "tu": "土突图", "tuan": "团",
    "tui": "推退", "tun": "吞", "tuo": "拖脱",
    "wa": "挖娃", "wai": "外", "wan": "完玩万晚", "wang": "王忘网",
    "wei": "为位未卫", "wen": "问文温", "weng": "翁", "wo": "我握窝",
    "wu": "五无物务",
    "xi": "系西习洗", "xia": "下夏吓", "xian": "现先线", "xiang": "想向香",
    "xiao": "小笑校", "xie": "写谢些", "xin": "心新信", "xing": "行兴星",
    "xiong": "兄熊", "xiu": "休秀", "xu": "需须许", "xuan": "选宣",
    "xue": "学雪", "xun": "寻训",
    "ya": "呀压牙", "yan": "眼严言颜", "yang": "样羊阳", "yao": "要摇药",
    "ye": "也夜业", "yi": "一以已意", "yin": "因音引", "ying": "应英硬",
    "yo": "哟", "yong": "用永勇", "you": "有又友由", "yu": "于与雨鱼",
    "yuan": "元原远", "yue": "月越", "yun": "云允",
    "za": "杂", "zai": "在再载", "zan": "暂赞", "zang": "藏",
    "zao": "早找枣", "ze": "则", "zei": "贼", "zen": "怎", "zeng": "增",
    "zha": "炸扎", "zhai": "摘", "zhan": "站战", "zhang": "张掌长",
    "zhao": "找照朝", "zhe": "这者", "zhen": "真阵", "zheng": "正整争",
    "zhi": "知只志纸", "zhong": "中重种", "zhou": "周州",
    "zhu": "主猪注", "zhua": "抓", "zhuai": "拽", "zhuan": "转专",
    "zhuang": "装状", "zhui": "追坠", "zhun": "准", "zhuo": "桌捉",
    "zi": "子字自", "zong": "总", "zou": "走", "zu": "组足",
    "zuan": "钻", "zui": "最嘴", "zun": "尊", "zuo": "做作坐左",
}

import json
import os

here = os.path.dirname(os.path.abspath(__file__))
out = {k: list(v) for k, v in PINYIN.items() if v}
path = os.path.join(here, "pinyin.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
print("生成 pinyin.json: 音节数=%d 文件大小=%d字节" %
      (len(out), len(json.dumps(out, ensure_ascii=False))))
print("示例 ni ->", out.get("ni"))
print("示例 wo ->", out.get("wo"))
print("示例 hao ->", out.get("hao"))
print("示例 shi ->", out.get("shi"))
